"""alert_place_id

Revision ID: a5052c07a840
Revises: b42fb4094fc3
Create Date: 2020-07-03 11:26:20.027996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5052c07a840'
down_revision = 'b42fb4094fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pair', 'placeId',
                    existing_type=sa.String(length=50),
                    type_=sa.CHAR(length=4),
                    comment='商店代號',
                    existing_nullable=False)
    op.alter_column('place', 'id',
                    existing_type=sa.String(length=50),
                    type_=sa.CHAR(length=4),
                    primary_key=True,
                    existing_comment='商店代號')
    op.alter_column('pool', 'placeId',
                    existing_type=sa.String(length=50),
                    type_=sa.CHAR(length=4),
                    existing_comment='商店代號',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool', 'placeId',
                    existing_type=sa.CHAR(length=4),
                    type_=sa.String(length=50),
                    existing_comment='商店代號',
                    existing_nullable=False)
    op.alter_column('place', 'id',
                    existing_type=sa.CHAR(length=4),
                    type_=sa.String(length=50),
                    primary_key=True,
                    existing_comment='商店代號')
    op.alter_column('pair', 'placeId',
                    existing_type=sa.CHAR(length=4),
                    type_=sa.String(length=50),
                    comment=None,
                    existing_comment='商店代號',
                    existing_nullable=False)
    # ### end Alembic commands ###
